/* SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Copyright (C) mrc-sk and imjumping
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version. See LICENSE for the full license text and the additional
 * non-commercial restriction terms that apply to this software.
 */
#include "berryos.h"
#include "fb.h"
#include "splash.h"

/* =====================================================================
 * Boot splash (M4): "BerrOS" wordmark + indeterminate loader.
 *
 * The reference boot animation is a black screen with the wordmark centred
 * and three short bright segments chasing each other along a full-width
 * track beneath it.  Bare metal cannot decode a video file, so the look is
 * reproduced natively: the wordmark is a paletted bitmap generated by
 * tools/make_splash_logo.py (blitted with a bilinear resample so one asset
 * fits any framebuffer resolution), and the bar is drawn from scratch each
 * frame.
 *
 * Geometry is measured off the reference frames rather than guessed (all
 * figures are fractions of the framebuffer):
 *   wordmark   top edge 28.5%, height 13.2%, width 47%, horizontally centred
 *   loader     core bar 1.65% tall, 39% of the width, top edge at 68.1%
 *              halo peaks at ~26% brightness and fades out over ~1.5%
 *              segment phase spacing 0.463W == (1 + 0.39) / 3, i.e. three
 *              segments evenly spaced across a full-width track
 *
 * Everything here is integer-only: the kernel is built -mno-sse, so touching
 * the x87/SSE register file would corrupt FPU state we never save.
 * =================================================================== */

extern const int splash_logo_w;
extern const int splash_logo_h;
extern const unsigned char splash_logo_pal[768];
extern const unsigned char splash_logo_idx[];

#define PIT_FREQ 1193182u

/* ---- timing: PIT channel 2 one-shot (usable with interrupts masked) ---- */
static int g_pit2_ok = 1;

/* Busy-wait us microseconds.  Channel 2 is re-armed per call, so -- unlike
 * channel 0, which the system tick keeps reloading -- there is no wrap
 * ambiguity no matter how long a frame takes to render.  If the emulator
 * (or chipset) does not expose the OUT2 status bit we give up after a bounded
 * spin and degrade to "frames as fast as possible" instead of hanging boot. */
static void delay_us(uint32_t us){
    uint32_t cnt, guard = 0;
    uint8_t p61;

    if (!g_pit2_ok || us == 0) return;
    cnt = (uint32_t)(((uint64_t)us * PIT_FREQ) / 1000000ull);
    if (cnt == 0) cnt = 1;
    if (cnt > 0xFFFFu) cnt = 0xFFFFu;             /* one-shot caps at ~54.9 ms */

    outb(0x43, 0xB0);                             /* ch2, mode 0, lo/hi, binary */
    outb(0x42, (uint8_t)(cnt & 0xFF));
    outb(0x42, (uint8_t)(cnt >> 8));
    p61 = inb(0x61);
    outb(0x61, (uint8_t)((p61 & 0xFC) | 0x01));   /* gate2 on, speaker off */
    while (!(inb(0x61) & 0x20)){                  /* wait for OUT2 high */
        if (++guard > 300000u){ g_pit2_ok = 0; return; }
    }
}

/* Any key press skips the splash.  IRQs are masked here, so nothing else is
 * draining the 8042: read the byte to unblock the controller, but only a
 * keyboard byte (AUX bit clear) counts.  Mouse bytes are simply discarded --
 * mouse_isr() resyncs on the packet-start bit, so that is harmless. */
static int key_pending(void){
    uint8_t st = inb(0x64);
    if (!(st & 0x01)) return 0;
    uint8_t aux = (uint8_t)(st & 0x20);
    (void)inb(0x60);
    return aux ? 0 : 1;
}

static uint32_t pal_rgb(int i){
    const unsigned char* p = &splash_logo_pal[(uint32_t)i * 3u];
    return ((uint32_t)p[0] << 16) | ((uint32_t)p[1] << 8) | (uint32_t)p[2];
}

/* Bilinear-resample the paletted wordmark into the framebuffer.  Fully black
 * source pixels are skipped -- the splash background is already black, so the
 * skip is invisible and it removes most of the work (the glyph box is largely
 * empty). */
static void blit_logo(int dx, int dy, int dw, int dh){
    int sw = splash_logo_w, sh = splash_logo_h;
    int x, y, ch;

    for (y = 0; y < dh; y++){
        uint32_t sy = (uint32_t)(((uint64_t)y << 16) * (uint32_t)sh / (uint32_t)dh);
        int y0 = (int)(sy >> 16);
        int y1 = (y0 + 1 < sh) ? y0 + 1 : sh - 1;
        int fy = (int)((sy & 0xFFFFu) >> 8);
        const unsigned char* r0 = &splash_logo_idx[(uint64_t)y0 * (uint32_t)sw];
        const unsigned char* r1 = &splash_logo_idx[(uint64_t)y1 * (uint32_t)sw];

        for (x = 0; x < dw; x++){
            uint32_t sx = (uint32_t)(((uint64_t)x << 16) * (uint32_t)sw / (uint32_t)dw);
            int x0 = (int)(sx >> 16);
            int x1 = (x0 + 1 < sw) ? x0 + 1 : sw - 1;
            int fx = (int)((sx & 0xFFFFu) >> 8);
            uint32_t c00 = pal_rgb(r0[x0]), c10 = pal_rgb(r0[x1]);
            uint32_t c01 = pal_rgb(r1[x0]), c11 = pal_rgb(r1[x1]);
            uint32_t out = 0;

            for (ch = 0; ch < 3; ch++){
                int shift = (ch == 0) ? 16 : (ch == 1 ? 8 : 0);
                int a = (int)((c00 >> shift) & 0xFF);
                int b = (int)((c10 >> shift) & 0xFF);
                int c = (int)((c01 >> shift) & 0xFF);
                int d = (int)((c11 >> shift) & 0xFF);
                int t0 = a + (((b - a) * fx) >> 8);
                int t1 = c + (((d - c) * fx) >> 8);
                int v  = t0 + (((t1 - t0) * fy) >> 8);
                out |= (uint32_t)(v & 0xFF) << shift;
            }
            if (out) fb_put_pixel(dx + x, dy + y, out);
        }
    }
}

/* One bright bar segment.  The core is a hard rectangle -- the reference
 * animation has crisp ends, not a fade -- and around it sits a soft halo that
 * peaks at HALO_PEAK brightness and decays linearly to nothing over `hn`
 * pixels.  Both axes share that profile, so the corner is just the product of
 * the two: a cheap stand-in for a small gaussian blur that costs a single
 * pass over the footprint. */
#define HALO_PEAK 67            /* ~26% of full scale, measured off the reference */

static void draw_segment(int bx, int by, int bw, int bh,
                         int x0, int segw, int hn){
    int cs = x0 - hn, ce = x0 + segw + hn;
    int col, row;

    if (cs < bx) cs = bx;
    if (ce > bx + bw) ce = bx + bw;
    if (cs >= ce) return;

    for (col = cs; col < ce; col++){
        int dxh = (col < x0) ? (x0 - col)
                : (col >= x0 + segw) ? (col - (x0 + segw) + 1) : 0;
        int hf;

        if (dxh >= hn) continue;
        hf = (dxh == 0) ? 255 : (hn - dxh) * HALO_PEAK / hn;

        for (row = by - hn; row < by + bh + hn; row++){
            int dyh = (row < by) ? (by - row)
                    : (row >= by + bh) ? (row - (by + bh) + 1) : 0;
            int vf;
            uint32_t a;

            if (dyh >= hn) continue;
            vf = (dyh == 0) ? 255 : (hn - dyh) * HALO_PEAK / hn;
            a = (uint32_t)(hf * vf) / 255u;
            if (!a) continue;
            fb_put_pixel(col, row, (a << 16) | (a << 8) | a);
        }
    }
}

/* Fade a rectangle toward black.  Sampled on a 2x2 grid -- at these dim
 * levels the blockiness is invisible and it quarters the cost. */
static void fade_box(int x, int y, int w, int h, int k){
    int i, j, di, dj;
    int xend = x + w, yend = y + h;

    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if (xend > (int)fb_width())  xend = (int)fb_width();
    if (yend > (int)fb_height()) yend = (int)fb_height();

    for (j = y; j < yend; j += 2){
        for (i = x; i < xend; i += 2){
            uint32_t c = fb_get_pixel(i, j);
            uint32_t r = (uint32_t)((((c >> 16) & 0xFF) * (uint32_t)k) / 255u);
            uint32_t g = (uint32_t)((((c >> 8)  & 0xFF) * (uint32_t)k) / 255u);
            uint32_t b = (uint32_t)((( c        & 0xFF) * (uint32_t)k) / 255u);
            uint32_t v = (r << 16) | (g << 8) | b;
            for (dj = 0; dj < 2; dj++){
                if (j + dj >= yend) break;
                for (di = 0; di < 2; di++){
                    if (i + di >= xend) break;
                    fb_put_pixel(i + di, j + dj, v);
                }
            }
        }
    }
}

/* Segment chase: three evenly spaced segments sweeping a full-width track.
 * The period is chosen so the sweep speed matches the reference animation
 * (~0.31 of the screen width per second); the phase spacing -- and therefore
 * how the loader reads -- follows from (bw + segw) / 3 and not from this. */
#define CHASE_MS 4500u
#define SEGMENTS 3

void splash_show(uint32_t total_ms){
    int W, H, lw, lh, lx, ly;
    int bw, bx, bh, by, hn, segw;
    int fx0, fy0, fw, fh;
    uint32_t elapsed = 0;
    int i;

    if (!g_fb.vbase) return;
    W = (int)fb_width();
    H = (int)fb_height();
    if (W < 64 || H < 64) return;

    /* Drain anything already sitting in the controller output buffer: a stale
     * byte must not be mistaken for "user pressed a key". */
    for (i = 0; i < 32 && (inb(0x64) & 0x01); i++) (void)inb(0x60);

    fb_clear(0x000000);

    /* ---- wordmark: 46% of the width, top edge at 26% of the height ---- */
    lw = (int)((int64_t)W * 46 / 100);
    if (lw > W - 32) lw = W - 32;
    lh = lw * splash_logo_h / splash_logo_w;
    lx = (W - lw) / 2;
    ly = (int)((int64_t)H * 26 / 100);
    blit_logo(lx, ly, lw, lh);

    /* ---- loader: full-width track, ~1.65% tall, top edge at 68.1% down ----
     * The track spans the whole screen, so segments get clipped by the screen
     * edges exactly as they do in the reference. */
    bw = W;
    bx = 0;
    bh = (int)((int64_t)H * 17 / 1000);
    if (bh < 3) bh = 3;
    by = (int)((int64_t)H * 681 / 1000);
    hn = (int)((int64_t)H * 15 / 1000);         /* how far the halo reaches */
    if (hn < 3) hn = 3;
    segw = (int)((int64_t)W * 39 / 100);

    /* The whole footprint the loader can touch.  Repainting only this band
     * (rather than the entire screen) keeps the frame cost low. */
    fx0 = bx - hn - 1;
    fy0 = by - hn - 1;
    fw  = bw + 2 * hn + 2;
    fh  = bh + 2 * hn + 2;
    if (fx0 < 0) { fw += fx0; fx0 = 0; }
    if (fy0 < 0) { fh += fy0; fy0 = 0; }
    if (fx0 + fw > W) fw = W - fx0;
    if (fy0 + fh > H) fh = H - fy0;

    /* ---- chase frames until the budget is spent (or a key arrives) ---- */
    for (;;){
        uint32_t tt = elapsed % CHASE_MS;

        fb_fill_rect(fx0, fy0, fw, fh, 0x000000);

        for (i = 0; i < SEGMENTS; i++){
            uint32_t ph = (uint32_t)(((uint64_t)tt + (uint64_t)i * CHASE_MS / SEGMENTS) % CHASE_MS);
            int x = (int)(((uint64_t)ph * (uint32_t)(bw + segw)) / CHASE_MS) - segw;
            draw_segment(bx, by, bw, bh, x, segw, hn);
        }

        delay_us(40000u);                       /* ~25 fps */
        elapsed += 40u;
        if (elapsed >= total_ms) break;
        if (key_pending()) break;
    }

    /* ---- short fade to black so the hand-off to the console is not a cut --- */
    for (i = 1; i <= 6; i++){
        int k = 255 - i * 255 / 6;
        fade_box(lx, ly, lw, lh, k);
        fade_box(fx0, fy0, fw, fh, k);
        delay_us(40000u);
    }
}
