#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) mrc-sk and imjumping
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See LICENSE for the full license text and the additional
# non-commercial restriction terms that apply to this software.
"""Embed one or more user ELF binaries as C arrays for the kernel.

Usage:
    python tools/embed_elf.py <name1> <in1.elf> [<name2> <in2.elf> ...] <out.c>

Each <name> becomes a pair of symbols in the generated C file:
    const unsigned char <name>_bin[];
    const unsigned int  <name>_len;
so the kernel can locate and load multiple user programs (e.g. an init
process and a worker it exec's).  The last argument is the output file.
"""
import sys


def main():
    # Total args = script + (name,elf) pairs + out.  The non-script portion
    # must be an odd count >= 3 (at least one name/elf pair plus the output).
    rest = len(sys.argv) - 1
    if rest < 3 or (rest % 2) != 1:
        print("usage: embed_elf.py <name1> <in1.elf> "
              "[<name2> <in2.elf> ...] <out.c>", file=sys.stderr)
        sys.exit(1)

    out_path = sys.argv[-1]
    pairs = sys.argv[1:-1]
    blobs = []
    for i in range(0, len(pairs), 2):
        name = pairs[i]
        elf_path = pairs[i + 1]
        with open(elf_path, "rb") as f:
            data = f.read()
        blobs.append((name, data))

    with open(out_path, "w") as f:
        f.write("/* Auto-generated by tools/embed_elf.py. DO NOT EDIT. */\n")
        f.write("#include \"berryos.h\"\n\n")
        for name, data in blobs:
            f.write("const unsigned char %s_bin[] = {\n" % name)
            for i in range(0, len(data), 12):
                chunk = data[i:i + 12]
                f.write("    " + ", ".join("0x%02x" % b for b in chunk) + ",\n")
            f.write("};\n\n")
            f.write("const unsigned int %s_len = %d;\n\n" % (name, len(data)))

    print("embedded %d blob(s) -> %s" % (len(blobs), out_path))


if __name__ == "__main__":
    main()
