#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright (C) mrc-sk and imjumping
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See LICENSE for the full license text and the additional
# non-commercial restriction terms that apply to this software.
"""Turn the BerryOS wordmark PNG into a kernel-linkable 8bpp paletted C array.

The boot splash (src/kernel/drivers/splash.c) blits this asset onto the VBE
linear framebuffer.  Storing it paletted (1 byte/pixel + a 768-byte palette)
keeps the kernel small: a 558x199 wordmark costs ~109 KiB of indices instead of
~327 KiB as raw RGB888 -- and the image is mostly black + silver text + a blue
orb, so 256 adaptive colours reproduce it almost exactly (mean abs error < 1).

Provenance of tools/assets/splash_logo.png
------------------------------------------
Cropped from the reference boot-animation video ("BerryOS.mp4", 1080x1080):

    frame    any settled frame, e.g. t = 12.75 s
             IMPORTANT: seek with `-ss <t> -i <video> -frames:v 1` lands
             BETWEEN keyframes and returns a blended, half-faded image.  The
             first version of this asset was cut from such a blend and its
             letters topped out at p95=157 instead of ~253, which made the
             on-screen wordmark visibly grey.  Decode from an earlier point and
             take a later frame (e.g. `-ss 10 -i v -vf select=gte(n\\,80)`)
             so the frame is real.
    crop     (265, 280) .. (823, 479)  ->  558 x 199
             i.e. the glyph bbox (290,308)..(798,450) padded 25 px horizontally
             and 28/29 px vertically so the orb's glow is not clipped.
    sanity   the crop must show max=255, p95=253 and ~7892 pixels >= 240,
             matching the source frame.

Usage:
    python tools/make_splash_logo.py \
        --src tools/assets/splash_logo.png \
        --out src/kernel/drivers/splash_logo.c

Regenerate whenever tools/assets/splash_logo.png changes.
"""
import argparse
import os
import numpy as np
from PIL import Image

HEADER = """/* SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Copyright (C) mrc-sk and imjumping
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version. See LICENSE for the full license text and the additional
 * non-commercial restriction terms that apply to this software.
 *
 * AUTO-GENERATED by tools/make_splash_logo.py -- DO NOT EDIT BY HAND.
 * Source image: {src}
 * Layout: splash_logo_pal[768] = 256 x {{R,G,B}}; splash_logo_idx[] = one palette
 * index per pixel, row-major, splash_logo_w x splash_logo_h.
 */
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="source PNG (RGB wordmark on black)")
    ap.add_argument("--out", required=True, help="generated C file")
    ap.add_argument("--colors", type=int, default=256)
    args = ap.parse_args()

    im = Image.open(args.src).convert("RGB")
    w, h = im.size
    q = im.quantize(colors=args.colors, method=Image.MEDIANCUT, dither=Image.NONE)
    pal = q.getpalette()[:256 * 3]
    pal += [0] * (256 * 3 - len(pal))            # pad to a full 256 entries
    idx = np.asarray(q, np.uint8)

    # quality report (so a bad palette is caught at generation time)
    rgb = np.asarray(q.convert("RGB")).astype(np.int16)
    ref = np.asarray(im).astype(np.int16)
    err = np.abs(rgb - ref)
    print("logo %dx%d  mean_err=%.2f  p99=%d  max=%d"
          % (w, h, err.mean(), np.percentile(err, 99), err.max()))

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER.format(src=args.src.replace("\\", "/")))
        f.write("\nconst int splash_logo_w = %d;\n" % w)
        f.write("const int splash_logo_h = %d;\n" % h)
        f.write("\nconst unsigned char splash_logo_pal[%d] = {\n" % len(pal))
        for i in range(0, len(pal), 12):
            f.write("    " + ",".join("%3d" % v for v in pal[i:i + 12]) + ",\n")
        f.write("};\n")
        flat = idx.reshape(-1)
        f.write("\nconst unsigned char splash_logo_idx[%d] = {\n" % flat.size)
        for i in range(0, flat.size, 24):
            f.write("    " + ",".join("%3d" % v for v in flat[i:i + 24]) + ",\n")
        f.write("};\n")
    print("wrote %s (%d palette + %d index bytes)"
          % (args.out, len(pal), flat.size))


if __name__ == "__main__":
    main()
